dist: xenial
language: go

env:
    - GO11MODULE=off

go:
    - 1.12.4

install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"

before_script:
    - go get -u github.com/gorilla/mux
    - go get -u github.com/ethereum/go-ethereum
    - go get -u github.com/jinzhu/gorm
    - go get -u github.com/dgrijalva/jwt-go
    - go get -u github.com/lib/pq

script:
    - go build -o service ./src/main/main.go
