dist: xenial
language: go

env:
    - GO11MODULE=on
    - GOFLAGS='-mod vendor'

go:
    - 1.12.4

install: false

before_script:
    - go get -u github.com/gorilla/mux
    - go get -u github.com/ethereum/go-ethereum
    - go get -u github.com/jinzhu/gorm
    - go get -u github.com/dgrijalva/jwt-go
    - go get -u github.com/lib/pq

script:
    - go test -v -race ./...
    - go build -o service ./src/main/main.go
